# main text of home
title: Long Nguyen
bio: Data Engineer

# twitter summary info
description: Blog sharing knowledge and experience of a happy programer.

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: auto

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
resume-url: https://google.com/?q=my+resume

url: https://longcnttbkhn.github.io

# your url: https://USERNAME.github.io

permalink: /:title/

analytics-google: G-DVYKM7CP8K

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: github # enter this from your disqus account
  categories: [] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
facebook: longnh95
linkedin: long-nguyen-hoang-9a631a113
github: longcnttbkhn
email: hoanglong180695@gmail.com

authors:
  johndoe:
    name: Long Nguyen
    bio: Backend and Data Engineer
    external-image: false
    picture: assets/images/profile.jpg
    linkedin: long-nguyen-hoang-9a631a113

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: false
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended

# if you don't need projects, comment the *projects* configs below
projects: false

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog, english]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-paginate-v2
  - jekyll-sitemap

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
